{"name": "test_login_1", "status": "skipped", "statusDetails": {"message": "AssertionError: assert False", "trace": "self = <scripts.test_login_xfail.TestLogin object at 0x000001A83A852978>\n\n    @pytest.mark.xfail(True,reason=\"条件成立跳过测试\")  # 4. 预期: 失败 结果: 失败\n    def test_login_1(self):\n        \"\"\"记住密码登录\"\"\"\n        print(\"test_login_1\")\n>       assert False\nE       assert False\n\nscripts\\test_login_xfail.py:18: AssertionError"}, "description": "记住密码登录", "start": 1575025869357, "stop": 1575025869357, "uuid": "212bc3c9-7ebc-4f3c-bedb-8b9055ac0d3d", "historyId": "3d3f777bc8201c33bfcb94f5f32bfe44", "testCaseId": "5ac8226c00d2d85bccc737b67a713045", "fullName": "scripts.test_login_xfail.TestLogin#test_login_1", "labels": [{"name": "parentSuite", "value": "scripts"}, {"name": "suite", "value": "test_login_xfail"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "DESKTOP-47A72RD"}, {"name": "thread", "value": "12696-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "scripts.test_login_xfail"}]}