{"name": "test_login_4", "status": "failed", "statusDetails": {"message": "AssertionError: assert False", "trace": "self = <scripts.test_login_xfail.TestLogin object at 0x000002C7D28F9748>\n\n    @pytest.mark.xfail(False, reason=\"条件成立跳过测试\")  # 2. 预期: 成功 结果: 失败\n    def test_login_4(self):\n        \"\"\"不记住密码登录\"\"\"\n        print(\"test_login_4\")\n>       assert False\nE       assert False\n\nscripts\\test_login_xfail.py:39: AssertionError"}, "description": "不记住密码登录", "start": 1575025966326, "stop": 1575025966326, "uuid": "ac336f39-6cd8-4cb4-819c-b3727d7542f7", "historyId": "ef72d7d3e035f1d427ca995d804cc9a8", "testCaseId": "153920b1612e7c5e11a83762e1a8ffb5", "fullName": "scripts.test_login_xfail.TestLogin#test_login_4", "labels": [{"name": "parentSuite", "value": "scripts"}, {"name": "suite", "value": "test_login_xfail"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "DESKTOP-47A72RD"}, {"name": "thread", "value": "6108-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "scripts.test_login_xfail"}]}